"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUp,ArrowDown,ArrowLeft,Volume2,VolumeX,Star,MessageCircle,X,RotateCcw,Home,Compass,Check,Trophy,Play,MapPin,Keyboard} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';

const missions=[
 {name:'Cikgu Aina',role:'Rancang pengajaran',x:600,y:300,portrait:1,color:'teal',greeting:'Hai, Guru Muda! Boleh bantu saya?',scenario:'Saya sedang merancang pengajaran. Saya perlu mengetahui perkara utama yang murid perlu ketahui dan boleh lakukan dalam sesuatu tempoh persekolahan.',question:'Bahagian DSKP manakah yang perlu saya rujuk?',correct:0,feedback:'Standard Kandungan menerangkan perkara yang murid patut ketahui dan boleh lakukan.',thanks:'Terima kasih, Guru Muda!',achievement:'MERANCANG'},
 {name:'Cikgu Amir',role:'Tetapkan pembelajaran',x:320,y:460,portrait:2,color:'gold',greeting:'Hai, Guru Muda!',scenario:'Saya sudah mengetahui kandungan yang perlu diajar. Sekarang saya mahu menentukan pembelajaran yang perlu dicapai oleh murid.',question:'Apakah yang perlu saya rujuk?',correct:1,feedback:'Standard Pembelajaran membantu menjelaskan pembelajaran yang perlu dicapai oleh murid.',thanks:'Bagus! Sekarang saya boleh merancang pembelajaran dengan lebih jelas.',achievement:'MENENTUKAN PEMBELAJARAN'},
 {name:'Cikgu Sara',role:'Nilai penguasaan',x:885,y:455,portrait:3,color:'coral',greeting:'Guru Muda, saya perlukan bantuan!',scenario:'Saya telah selesai menjalankan PdP. Sekarang saya mahu menentukan tahap penguasaan murid.',question:'Bahagian DSKP manakah yang perlu saya rujuk?',correct:2,feedback:'Standard Prestasi digunakan sebagai rujukan untuk menentukan tahap penguasaan murid.',thanks:'Syabas, Guru Muda!',achievement:'MENILAI PENGUASAAN'}
];
const answers=['Standard Kandungan (SK)','Standard Pembelajaran (SP)','Standard Prestasi'];
const obstacles=[{x:0,y:0,w:1200,h:165},{x:0,y:355,w:215,h:212},{x:1000,y:355,w:200,h:212},{x:0,y:680,w:500,h:120},{x:705,y:680,w:495,h:120}];
const initial={x:605,y:650};
type Phase='menu'|'intro'|'play'|'question'|'wrong'|'correct'|'done'|'final';
function Avatar({index=0,className=''}:{index?:number;className?:string}){return <span aria-hidden="true" className={`avatar avatar-${index} ${className}`}/>;}

export default function Game(){
 const [phase,setPhase]=useState<Phase>('menu'),[complete,setComplete]=useState<number[]>([]),[active,setActive]=useState(0),[near,setNear]=useState<number|null>(null),[sound,setSound]=useState(false),[loaded,setLoaded]=useState(false),[assetError,setAssetError]=useState(false),[stick,setStick]=useState({x:0,y:0}),[pulse,setPulse]=useState(0);
 const stage=useRef<HTMLDivElement>(null),world=useRef<HTMLDivElement>(null),player=useRef<HTMLDivElement>(null);
 const position=useRef({...initial}),keys=useRef(new Set<string>()),joystick=useRef({x:0,y:0}),phaseRef=useRef<Phase>('menu'),nearRef=useRef<number|null>(null),completeRef=useRef<number[]>([]),soundRef=useRef(false),audio=useRef<AudioContext|null>(null),captured=useRef<number|null>(null);
 const current=missions[active],modal=['intro','question','wrong','correct','done','final'].includes(phase);
 function transition(p:Phase){phaseRef.current=p;setPhase(p);keys.current.clear();joystick.current={x:0,y:0};setStick({x:0,y:0});}
 function tone(kind='click'){if(!soundRef.current)return;try{audio.current??=new AudioContext();const c=audio.current;void c.resume();(kind==='final'?[523,659,784,1047]:kind==='success'?[523,659,784]:[420]).forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.11;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.07,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.25);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+.27);});}catch{}}
 function reset(menu=false){completeRef.current=[];setComplete([]);position.current={...initial};nearRef.current=null;setNear(null);setActive(0);setPulse(0);transition(menu?'menu':'intro');}
 function interact(){if(phaseRef.current!=='play'||nearRef.current===null)return;const i=nearRef.current;setActive(i);tone();transition(completeRef.current.includes(i)?'done':'question');}
 function answer(i:number){if(phaseRef.current!=='question')return;if(i!==missions[active].correct){transition('wrong');tone();return;}if(!completeRef.current.includes(active)){completeRef.current=[...completeRef.current,active];setComplete([...completeRef.current]);setPulse(x=>x+1);}if(completeRef.current.length===3){tone('final');transition('final');}else{tone('success');transition('correct');}}
 function moveJoy(e:React.PointerEvent<HTMLDivElement>){if(phaseRef.current!=='play'||captured.current!==e.pointerId)return;const b=e.currentTarget.getBoundingClientRect();let dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2;const d=Math.hypot(dx,dy),limit=39;if(d>limit){dx*=limit/d;dy*=limit/d;}joystick.current={x:dx/limit,y:dy/limit};setStick({x:dx,y:dy});}
 function stopJoy(){captured.current=null;joystick.current={x:0,y:0};setStick({x:0,y:0});}
 useEffect(()=>{let cancel=false;Promise.all(['/school.webp','/characters.webp'].map(src=>new Promise<void>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve();img.onerror=reject;img.src=src;}))).then(()=>{if(!cancel)setLoaded(true);}).catch(()=>{if(!cancel)setAssetError(true);});return()=>{cancel=true;};},[]);
 useEffect(()=>{
  const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(phaseRef.current==='play'&&['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e',' '].includes(k)){e.preventDefault();if(k==='e'&&!e.repeat)interact();else keys.current.add(k);}};
  const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase()),clear=()=>{keys.current.clear();stopJoy();};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);
  let frame=0,last=0,previousNear:number|null=null;const camera={x:0,y:0};
  const blocked=(x:number,y:number)=>x<65||x>1135||y<185||y>750||obstacles.some(r=>x+15>r.x&&x-15<r.x+r.w&&y+9>r.y&&y-9<r.y+r.h)||missions.some(n=>Math.hypot(x-n.x,y-n.y)<30);
  const tick=(time:number)=>{const dt=Math.min((time-last)/1000||0,.035);last=time;const el=stage.current,w=world.current,p=player.current;if(el&&w&&p){let dx=0,dy=0;if(phaseRef.current==='play'){dx=(keys.current.has('d')||keys.current.has('arrowright')?1:0)-(keys.current.has('a')||keys.current.has('arrowleft')?1:0)+joystick.current.x;dy=(keys.current.has('s')||keys.current.has('arrowdown')?1:0)-(keys.current.has('w')||keys.current.has('arrowup')?1:0)+joystick.current.y;const mag=Math.hypot(dx,dy);if(mag>1){dx/=mag;dy/=mag;}const nx=position.current.x+dx*210*dt,ny=position.current.y+dy*210*dt;if(!blocked(nx,position.current.y))position.current.x=nx;if(!blocked(position.current.x,ny))position.current.y=ny;}
   const px=position.current.x,py=position.current.y;p.style.left=`${px}px`;p.style.top=`${py}px`;p.style.setProperty('--bounce',Math.hypot(dx,dy)>.1?`${Math.sin(time*.019)*3}px`:'0px');p.style.zIndex=String(Math.round(py));p.dataset.x=px.toFixed(1);p.dataset.y=py.toFixed(1);
   let ni:number|null=null,min=100;missions.forEach((n,i)=>{const d=Math.hypot(px-n.x,py-n.y);if(d<min){min=d;ni=i;}});nearRef.current=ni;if(ni!==previousNear){previousNear=ni;setNear(ni);}
   const vw=el.clientWidth,vh=el.clientHeight,scale=Math.max(.7,Math.min(vw/450,vh/800)),bw=1200*scale,bh=800*scale,tx=bw<=vw?(vw-bw)/2:Math.max(vw-bw,Math.min(0,vw/2-px*scale)),ty=bh<=vh?(vh-bh)/2:Math.max(vh-bh,Math.min(0,vh*.56-py*scale)),smooth=1-Math.exp(-dt*10);camera.x+=(tx-camera.x)*smooth;camera.y+=(ty-camera.y)*smooth;w.style.transform=`translate(${camera.x}px,${camera.y}px) scale(${scale})`;
  }frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);};
 },[]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options?:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const tools=[{name:'read_mission_progress',description:'Read Checkpoint 4 progress and the nearby teacher.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({phase:phaseRef.current,completed:completeRef.current.map(i=>missions[i].name),nearby:nearRef.current===null?null:missions[nearRef.current].name})},{name:'start_dskp_adventure',description:'Start a new DSKP adventure from the main menu only.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(phaseRef.current!=='menu')throw new Error('Permainan telah bermula.');reset();return{phase:'intro'};}}];tools.forEach(t=>{try{void Promise.resolve(context.registerTool(t,{signal:controller.signal})).catch(()=>{});}catch{}});return()=>controller.abort();},[]);
 return <main className={`game-shell ${phase==='menu'?'is-menu':''}`}>
  <header className="hud"><div className="brand"><span className="brand-icon"><Compass size={25}/></span><div><strong>CABARAN GURU MUDA</strong><span>MISI DSKP <i/> CHECKPOINT 4</span></div></div><div className="hud-right"><div className="mission-count" aria-live="polite"><Star size={22} fill="currentColor"/><span>MISI: <b>{complete.length}/3</b></span></div><Button className="sound-toggle" variant="ghost" aria-label={sound?'Matikan bunyi':'Hidupkan bunyi'} aria-pressed={sound} onClick={()=>{soundRef.current=!sound;setSound(!sound);if(!sound)tone();}}>{sound?<Volume2/>:<VolumeX/>}</Button></div></header>
  <div className="stage" ref={stage} aria-label="Peta sekolah. Gerak dengan WASD, kekunci anak panah atau kayu bedik."><div className="world" ref={world}>
   <img className="school-map" src="/school.webp" alt="Sekolah Ilmu Ceria dengan laluan taman dan ruang pembelajaran" draggable="false"/>
   <div className="school-sign">SEKOLAH ILMU CERIA</div><span className="map-sign sign-a">BILIK KURIKULUM</span><span className="map-sign sign-b">RUANG PEMBELAJARAN</span><span className="map-sign sign-c">RUANG PENTAKSIRAN</span>
   {missions.map((m,i)=><div key={m.name} className={`npc ${m.color} ${near===i?'nearby':''} ${complete.includes(i)?'completed':''}`} style={{left:m.x,top:m.y,zIndex:Math.round(m.y)}}><span className="npc-indicator">{complete.includes(i)?<Check size={19} strokeWidth={3}/>:<span>!</span>}</span><Avatar index={m.portrait}/><span className="npc-name">{m.name}</span><span className="npc-task">{i+1} · {m.role}</span></div>)}
   <div ref={player} className="player" style={{left:initial.x,top:initial.y}}><span className="player-label">ANDA</span><Avatar/><span className="player-ground"/></div>
  </div></div>
  {phase!=='menu'&&<><div className="explore-info"><div className="explore-heading"><Compass size={18}/><span>{complete.length===0?'Jelajah sekolah. Cari guru pertama anda.':`Bagus! Cari ${3-complete.length} guru lagi.`}</span></div><div className="mission-chips">{missions.map((m,i)=><span className={complete.includes(i)?'chip is-done':'chip'} key={m.name}>{complete.includes(i)?<Check size={14}/>:<span className={`chip-dot ${m.color}`}/>} {m.name.replace('Cikgu ','')}</span>)}</div></div>
   <div className={`controls ${modal?'controls-hidden':''}`}><div className="movement"><div className="joystick" role="group" aria-label="Kayu bedik pergerakan" onPointerDown={e=>{if(captured.current!==null)return;captured.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);moveJoy(e);}} onPointerMove={moveJoy} onPointerUp={stopJoy} onPointerCancel={stopJoy} onLostPointerCapture={stopJoy}><ArrowUp className="joy-up"/><ArrowDown className="joy-down"/><ArrowLeft className="joy-left"/><ArrowRight className="joy-right"/><span className="joy-knob" style={{transform:`translate(${stick.x}px,${stick.y}px)`}}/></div><span className="keyboard-help"><Keyboard size={16}/> WASD / kekunci arah</span></div><div className="interact-area"><div className="proximity" aria-live="polite">{near!==null?<><span className="proximity-dot"/>{missions[near].name}</>:<><MapPin size={15}/> Dekati seorang guru</>}</div><Button className="interact-btn" disabled={near===null||phase!=='play'} onClick={interact}><MessageCircle size={22}/> BERBUAL <kbd>E</kbd></Button></div></div>
   <footer className="world-footer"><span>JELAJAH · BANTU · BERJAYA</span><span>Pilih mana-mana guru untuk bermula</span></footer></>}
  {phase==='menu'&&<section className="menu-screen"><div className="menu-card"><div className="eyebrow"><span/> CHECKPOINT 4 · CABARAN AKHIR</div><h1>CABARAN<br/>GURU MUDA<span>MISI DSKP<span className="title-star">✦</span></span></h1><p className="menu-description">Lengkapkan 3 misi dan buktikan anda bersedia menjadi Guru Muda DSKP!</p><div className="menu-steps"><span>🕹️ Jelajah kawasan sekolah</span><span>👩‍🏫 Cari 3 orang guru</span><span>💬 Tekan BERBUAL</span><span>🧠 Selesaikan cabaran</span><span>⭐ Kumpulkan 3 bintang</span></div><Button className="primary-btn start-btn" disabled={!loaded} onClick={()=>{tone();reset();}}><Play size={20} fill="currentColor"/>{loaded?'MULA MISI':assetError?'GAMBAR BELUM DIMUATKAN':'MENYEDIAKAN SEKOLAH…'}<ArrowRight size={20}/></Button>{assetError&&<Button variant="ghost" onClick={()=>location.reload()}>Cuba muat semula</Button>}<div className="menu-meta"><span>◷ 3–5 minit</span><span>3 guru · 3 bintang</span></div></div><div className="menu-hero"><span className="hero-star star-one">✦</span><span className="hero-star star-two">✦</span><span className="hero-star star-three">✧</span><Avatar/><div className="hero-badge"><Star fill="currentColor"/><span>GURU MUDA<br/><b>Sedia untuk cabaran?</b></span></div></div><p className="menu-footer">Pameran Inovasi Pendidikan · Pengukuhan & penilaian kendiri</p></section>}
  <Dialog open={modal} onOpenChange={open=>{if(!open&&['question','wrong','done'].includes(phaseRef.current))transition('play');}}><DialogContent className={`game-dialog ${phase==='final'?'final-dialog':''}`} showCloseButton={false} onEscapeKeyDown={e=>{if(!['question','wrong','done'].includes(phaseRef.current))e.preventDefault();}} onPointerDownOutside={e=>e.preventDefault()}>
   {['question','wrong','done'].includes(phase)&&<Button className="dialog-close" variant="ghost" aria-label="Tutup perbualan" onClick={()=>transition('play')}><X size={20}/></Button>}
   {phase==='intro'?<><div className="dialog-intro-icon"><Compass size={38}/></div><p className="eyebrow">PENGEMBARAAN ANDA BERMULA</p><DialogTitle className="dialog-title">Selamat datang,<br/>Guru Muda!</DialogTitle><DialogDescription className="dialog-copy">Hari ini, tiga orang guru memerlukan bantuan anda. Gunakan pengetahuan DSKP anda untuk membantu mereka membuat keputusan yang tepat.</DialogDescription><div className="intro-tip">⭐ Lengkapkan ketiga-tiga misi untuk memperoleh 3 bintang!</div><p className="mini-help">Gerak dengan WASD / kekunci arah atau kayu bedik. Dekati guru, kemudian tekan BERBUAL atau E.</p><Button className="primary-btn" onClick={()=>{transition('play');tone();}}>🚀 MULAKAN CABARAN</Button></>:
   phase==='final'?<><div className="confetti" aria-hidden="true">{Array.from({length:24},(_,i)=><i key={`${pulse}-${i}`} style={{left:`${(i*43)%100}%`,animationDelay:`${i*.05}s`,background:['#ffd260','#16a38d','#fb876a'][i%3]}}/>)}</div><div className="trophy"><Trophy size={42}/></div><p className="eyebrow">TAHNIAH, GURU MUDA!</p><DialogTitle className="dialog-title">Cabaran Guru Muda<br/>selesai!</DialogTitle><div className="final-stars" aria-label="Tiga bintang">{[0,1,2].map(i=><Star key={i} fill="currentColor" size={42}/>)}</div><strong className="final-count">3/3 MISI SELESAI</strong><DialogDescription className="dialog-copy">Anda berjaya menggunakan pengetahuan DSKP dalam situasi PdP.</DialogDescription><div className="achievements">{missions.map((m,i)=><div key={m.name}><span>{['🎯','📚','📊'][i]}</span><div><b>{m.achievement}</b><p>{answers[i].replace(/ \(.*\)/,'')}</p></div><Check size={18}/></div>)}</div><p className="final-message">Syabas, Guru Muda! Anda telah berjaya menyelesaikan Misi DSKP.</p><div className="final-buttons"><Button className="primary-btn" onClick={()=>reset()}><RotateCcw size={18}/> MAIN SEMULA</Button><Button variant="ghost" className="secondary-btn" onClick={()=>reset(true)}><Home size={18}/> KEMBALI KE MENU</Button></div></>:
   <><div className={`teacher-heading ${current.color}`}><div className="teacher-portrait"><Avatar index={current.portrait}/></div><div><p className="eyebrow">{phase==='correct'?'⭐ MISI SELESAI!':phase==='done'?'✓ MISI TELAH SELESAI':`MISI ${active+1} DARIPADA 3`}</p><DialogTitle className="teacher-name">{current.name}</DialogTitle><span>{current.role}</span></div></div>
    {phase==='question'?<><DialogDescription className="dialog-copy scenario"><span className="greeting">{current.greeting}</span>{current.scenario}</DialogDescription><h2 className="question">{current.question}</h2><div className="answers">{answers.map((a,i)=><Button key={a} variant="outline" className="answer-card" onClick={()=>answer(i)}><span className="answer-letter">{'ABC'[i]}</span><span>{a}</span><ArrowRight size={18}/></Button>)}</div><p className="no-pressure">Fikir dahulu. Anda boleh mencuba lagi.</p></>:
    phase==='wrong'?<><div className="feedback-icon">🤔</div><h2 className="feedback-title">Belum tepat!</h2><DialogDescription className="dialog-copy">Fikir semula situasi yang diberikan.</DialogDescription><p className="retry-scenario">“{current.scenario}”</p><Button className="primary-btn" onClick={()=>transition('question')}><RotateCcw size={18}/> CUBA LAGI</Button></>:
    <><div className="success-star"><Star size={54} fill="currentColor"/></div><h2 className="feedback-title">{phase==='done'?'Anda sudah membantu saya!':['BETUL! 🎉','TEPAT! 🎉','HEBAT! 🎉'][active]}</h2><DialogDescription className="dialog-copy">{current.feedback}</DialogDescription><p className="teacher-thanks">“{current.thanks}”</p><div className="earned">{phase==='correct'?'⭐ +1 BINTANG':'✅ Bintang misi ini sudah dikumpulkan'}</div><Button className="primary-btn" onClick={()=>transition('play')}>TERUSKAN JELAJAH <ArrowRight size={18}/></Button></>}
   </>}
  </DialogContent></Dialog>
 </main>;
}
